"""
Strategy C Focused Visualizer - Technology & Knowledge Sharing Analysis
========================================================================
This visualizer creates focused charts for Strategy C (Zone III - Learning Zone)
analyzing technology effectiveness and knowledge sharing initiatives.

Zone III Focus: Low-emission, high-cooperation suppliers
- Technology effectiveness analysis
- Knowledge initiative impact
- Success rate correlation
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib import rcParams
import numpy as np
import os

# Chinese font configuration
rcParams['font.sans-serif'] = ['SimHei', 'Arial Unicode MS', 'PingFang SC', 'STHeiti']
rcParams['axes.unicode_minus'] = False

# ============================================================================
# Data Loading
# ============================================================================

def load_data():
    """Load all CSV files generated by the ML simulation"""
    
    try:
        budget_df = pd.read_csv('ML_simulation_C_投资预算分配.csv', encoding='utf-8-sig')
        tech_db = pd.read_csv('ML_simulation_C_技术数据库.csv', encoding='utf-8-sig')
        knowledge_db = pd.read_csv('ML_simulation_C_知识共享数据库.csv', encoding='utf-8-sig')
        summary_df = pd.read_csv('ML_simulation_C_strategy_summary.csv', encoding='utf-8-sig')
        
        print("✓ All data files loaded successfully")
        return budget_df, tech_db, knowledge_db, summary_df
        
    except FileNotFoundError as e:
        print(f"❌ Error: Could not find data file: {e}")
        print("Please run C_strategy_ML_simulation.py first to generate the data files.")
        return None, None, None, None


# ============================================================================
# Chart 1: Technology Effectiveness (技术减排效果)
# ============================================================================

def plot_technology_effectiveness(tech_db):
    """Plot horizontal bar chart showing technology effectiveness by reduction rate"""
    
    fig, ax = plt.subplots(figsize=(10, 8))
    
    # Sort technologies by reduction rate
    tech_db_sorted = tech_db.sort_values('减排率', ascending=True)
    
    # Create color gradient from light to dark green
    colors_tech = plt.cm.YlGn(np.linspace(0.4, 0.9, len(tech_db_sorted)))
    
    # Create horizontal bar chart
    y_pos = np.arange(len(tech_db_sorted))
    bars = ax.barh(y_pos, tech_db_sorted['减排率'] * 100,
                   color=colors_tech, alpha=0.85, edgecolor='black', linewidth=1.2)
    
    # Set labels
    ax.set_yticks(y_pos)
    ax.set_yticklabels(tech_db_sorted['技术名称'], fontsize=11)
    ax.set_xlabel('减排率 (%)', fontsize=13, weight='bold')
    ax.set_title('技术减排效果\nTechnology Effectiveness', fontsize=15, weight='bold', pad=20)
    ax.grid(True, alpha=0.3, axis='x', linestyle='--')
    
    # Add value labels on bars
    for i, (bar, value) in enumerate(zip(bars, tech_db_sorted['减排率'] * 100)):
        ax.text(value + 0.15, i, f'{value:.1f}%',
                va='center', ha='left', fontsize=9, weight='bold')
    
    plt.tight_layout()
    
    output_path = 'C区_技术减排效果.png'
    plt.savefig(output_path, dpi=300, bbox_inches='tight', facecolor='white')
    print(f"✓ Chart 1 saved: {output_path}")
    
    return fig


# ============================================================================
# Chart 2: Knowledge Transfer vs Reduction (知识转移与减排效果)
# ============================================================================

def plot_knowledge_transfer_vs_reduction(budget_df):
    """Plot scatter chart showing correlation between knowledge transfer score and reduction rate"""
    
    fig, ax = plt.subplots(figsize=(10, 8))
    
    # Create scatter plot with bubble size based on total investment
    scatter = ax.scatter(budget_df['知识转移得分'],
                        budget_df['减排率'],
                        s=budget_df['总投资'] * 0.8,  # Bubble size
                        c=budget_df['配合程度'] if '配合程度' in budget_df.columns else budget_df['知识倍增器'],
                        cmap='plasma',
                        alpha=0.6,
                        edgecolors='black',
                        linewidth=1.5)
    
    # Set labels and title
    ax.set_xlabel('知识转移得分 (Knowledge Transfer Score)', fontsize=13, weight='bold')
    ax.set_ylabel('减排率 (%)', fontsize=13, weight='bold')
    ax.set_title('知识转移与减排效果\nKnowledge Transfer vs Reduction', fontsize=15, weight='bold', pad=20)
    ax.grid(True, alpha=0.3, linestyle='--')
    
    # Add colorbar
    cbar = plt.colorbar(scatter, ax=ax)
    cbar.set_label('配合程度' if '配合程度' in budget_df.columns else '知识倍增器', 
                   fontsize=11, weight='bold')
    
    # Add trend line
    z = np.polyfit(budget_df['知识转移得分'], budget_df['减排率'], 1)
    p = np.poly1d(z)
    x_trend = np.linspace(budget_df['知识转移得分'].min(), budget_df['知识转移得分'].max(), 100)
    ax.plot(x_trend, p(x_trend), "r--", alpha=0.8, linewidth=2, label='趋势线')
    ax.legend(fontsize=10)
    
    plt.tight_layout()
    
    output_path = 'C区_知识转移与减排效果.png'
    plt.savefig(output_path, dpi=300, bbox_inches='tight', facecolor='white')
    print(f"✓ Chart 2 saved: {output_path}")
    
    return fig


# ============================================================================
# Chart 3: Knowledge Initiative Impact (知识共享倡议效果)
# ============================================================================

def plot_knowledge_initiative_impact(knowledge_db):
    """Plot grouped bar chart showing knowledge multiplier and network effect for each initiative"""
    
    fig, ax = plt.subplots(figsize=(12, 7))
    
    # Prepare data
    x_pos = np.arange(len(knowledge_db))
    width = 0.35
    
    # Create grouped bars
    bars1 = ax.bar(x_pos - width/2, knowledge_db['知识倍增器'],
                   width, label='知识倍增器', color='steelblue', alpha=0.85, edgecolor='black', linewidth=1.2)
    bars2 = ax.bar(x_pos + width/2, knowledge_db['网络效应'],
                   width, label='网络效应', color='orange', alpha=0.85, edgecolor='black', linewidth=1.2)
    
    # Set labels and title
    ax.set_xticks(x_pos)
    ax.set_xticklabels(knowledge_db['倡议名称'], rotation=30, ha='right', fontsize=10)
    ax.set_ylabel('效果值', fontsize=13, weight='bold')
    ax.set_title('知识共享倡议效果\nKnowledge Initiative Impact', fontsize=15, weight='bold', pad=20)
    ax.legend(fontsize=11, loc='upper left')
    ax.grid(True, alpha=0.3, axis='y', linestyle='--')
    
    # Add value labels on bars
    for bars in [bars1, bars2]:
        for bar in bars:
            height = bar.get_height()
            ax.text(bar.get_x() + bar.get_width()/2., height,
                   f'{height:.2f}',
                   ha='center', va='bottom', fontsize=9, weight='bold')
    
    plt.tight_layout()
    
    output_path = 'C区_知识共享倡议效果.png'
    plt.savefig(output_path, dpi=300, bbox_inches='tight', facecolor='white')
    print(f"✓ Chart 3 saved: {output_path}")
    
    return fig


# ============================================================================
# Chart 4: Initiatives vs Success Rate (倡议数量与成功率)
# ============================================================================

def plot_initiatives_vs_success_rate(budget_df, summary_df):
    """Plot line/bar chart showing relationship between number of initiatives and success rate"""
    
    fig, ax = plt.subplots(figsize=(10, 7))
    
    # Merge dataframes
    merged_data = pd.merge(budget_df, summary_df, on='供应商')
    
    # Calculate success rate by initiative count
    initiative_success = merged_data.groupby('知识倡议数').agg({
        '是否达标': lambda x: (x == '是').sum() / len(x) * 100 if len(x) > 0 else 0,
        '供应商': 'count'  # Count of suppliers
    }).reset_index()
    initiative_success.columns = ['知识倡议数量', '达标率', '供应商数量']
    
    # Create bar chart
    bars = ax.bar(initiative_success['知识倡议数量'], 
                  initiative_success['达标率'],
                  color='seagreen', alpha=0.8, edgecolor='black', linewidth=1.5,
                  width=0.6)
    
    # Add line connecting the bars
    ax.plot(initiative_success['知识倡议数量'], initiative_success['达标率'],
           color='darkgreen', marker='o', linewidth=2.5, markersize=8, alpha=0.7)
    
    # Set labels and title
    ax.set_xlabel('知识倡议数量', fontsize=13, weight='bold')
    ax.set_ylabel('达标率 (%)', fontsize=13, weight='bold')
    ax.set_title('倡议数量与成功率\nInitiatives vs Success Rate', fontsize=15, weight='bold', pad=20)
    ax.grid(True, alpha=0.3, axis='y', linestyle='--')
    
    # Set x-axis to show integer ticks
    ax.set_xticks(initiative_success['知识倡议数量'])
    
    # Add value labels on bars
    for i, (bar, value, count) in enumerate(zip(bars, initiative_success['达标率'], initiative_success['供应商数量'])):
        height = bar.get_height()
        # Show percentage
        ax.text(bar.get_x() + bar.get_width()/2., height + 0.5,
               f'{value:.1f}%',
               ha='center', va='bottom', fontsize=10, weight='bold')
        # Show supplier count below x-axis
        ax.text(bar.get_x() + bar.get_width()/2., -2,
               f'n={int(count)}',
               ha='center', va='top', fontsize=9, style='italic', color='gray')
    
    # Adjust y-axis to make room for labels
    y_max = initiative_success['达标率'].max()
    ax.set_ylim(-5, y_max * 1.15)
    
    plt.tight_layout()
    
    output_path = 'C区_倡议数量与成功率.png'
    plt.savefig(output_path, dpi=300, bbox_inches='tight', facecolor='white')
    print(f"✓ Chart 4 saved: {output_path}")
    
    return fig


# ============================================================================
# Combined Figure: All 4 Charts in One Layout (Optional)
# ============================================================================

def plot_all_combined(budget_df, tech_db, knowledge_db, summary_df):
    """Create a combined figure with all 4 charts"""
    
    fig = plt.figure(figsize=(18, 14))
    gs = fig.add_gridspec(2, 2, hspace=0.35, wspace=0.3)
    
    # Chart 1: Technology Effectiveness (Top Left)
    ax1 = fig.add_subplot(gs[0, 0])
    tech_db_sorted = tech_db.sort_values('减排率', ascending=True)
    colors_tech = plt.cm.YlGn(np.linspace(0.4, 0.9, len(tech_db_sorted)))
    y_pos = np.arange(len(tech_db_sorted))
    bars1 = ax1.barh(y_pos, tech_db_sorted['减排率'] * 100,
                     color=colors_tech, alpha=0.85, edgecolor='black', linewidth=1)
    ax1.set_yticks(y_pos)
    ax1.set_yticklabels(tech_db_sorted['技术名称'], fontsize=9)
    ax1.set_xlabel('减排率 (%)', fontsize=11, weight='bold')
    ax1.set_title('技术减排效果\nTechnology Effectiveness', fontsize=13, weight='bold', pad=15)
    ax1.grid(True, alpha=0.3, axis='x', linestyle='--')
    
    # Chart 2: Knowledge Transfer vs Reduction (Top Right)
    ax2 = fig.add_subplot(gs[0, 1])
    scatter = ax2.scatter(budget_df['知识转移得分'],
                         budget_df['减排率'],
                         s=budget_df['总投资'] * 0.8,
                         c=budget_df['知识倍增器'],
                         cmap='plasma',
                         alpha=0.6,
                         edgecolors='black',
                         linewidth=1)
    ax2.set_xlabel('知识转移得分 (Knowledge Transfer Score)', fontsize=11, weight='bold')
    ax2.set_ylabel('减排率 (%)', fontsize=11, weight='bold')
    ax2.set_title('知识转移与减排效果\nKnowledge Transfer vs Reduction', fontsize=13, weight='bold', pad=15)
    ax2.grid(True, alpha=0.3, linestyle='--')
    cbar = plt.colorbar(scatter, ax=ax2)
    cbar.set_label('知识倍增器', fontsize=9)
    
    # Add trend line
    z = np.polyfit(budget_df['知识转移得分'], budget_df['减排率'], 1)
    p = np.poly1d(z)
    x_trend = np.linspace(budget_df['知识转移得分'].min(), budget_df['知识转移得分'].max(), 100)
    ax2.plot(x_trend, p(x_trend), "r--", alpha=0.8, linewidth=2)
    
    # Chart 3: Knowledge Initiative Impact (Bottom Left)
    ax3 = fig.add_subplot(gs[1, 0])
    x_pos = np.arange(len(knowledge_db))
    width = 0.35
    bars3a = ax3.bar(x_pos - width/2, knowledge_db['知识倍增器'],
                     width, label='知识倍增器', color='steelblue', alpha=0.85, edgecolor='black')
    bars3b = ax3.bar(x_pos + width/2, knowledge_db['网络效应'],
                     width, label='网络效应', color='orange', alpha=0.85, edgecolor='black')
    ax3.set_xticks(x_pos)
    ax3.set_xticklabels(knowledge_db['倡议名称'], rotation=25, ha='right', fontsize=9)
    ax3.set_ylabel('效果值', fontsize=11, weight='bold')
    ax3.set_title('知识共享倡议效果\nKnowledge Initiative Impact', fontsize=13, weight='bold', pad=15)
    ax3.legend(fontsize=10)
    ax3.grid(True, alpha=0.3, axis='y', linestyle='--')
    
    # Chart 4: Initiatives vs Success Rate (Bottom Right)
    ax4 = fig.add_subplot(gs[1, 1])
    merged_data = pd.merge(budget_df, summary_df, on='供应商')
    initiative_success = merged_data.groupby('知识倡议数').agg({
        '是否达标': lambda x: (x == '是').sum() / len(x) * 100 if len(x) > 0 else 0
    }).reset_index()
    initiative_success.columns = ['知识倡议数量', '达标率']
    
    bars4 = ax4.bar(initiative_success['知识倡议数量'], 
                   initiative_success['达标率'],
                   color='seagreen', alpha=0.8, edgecolor='black', linewidth=1.5)
    ax4.plot(initiative_success['知识倡议数量'], initiative_success['达标率'],
            color='darkgreen', marker='o', linewidth=2.5, markersize=8, alpha=0.7)
    ax4.set_xlabel('知识倡议数量', fontsize=11, weight='bold')
    ax4.set_ylabel('达标率 (%)', fontsize=11, weight='bold')
    ax4.set_title('倡议数量与成功率\nInitiatives vs Success Rate', fontsize=13, weight='bold', pad=15)
    ax4.grid(True, alpha=0.3, axis='y', linestyle='--')
    ax4.set_xticks(initiative_success['知识倡议数量'])
    
    for bar, value in zip(bars4, initiative_success['达标率']):
        height = bar.get_height()
        ax4.text(bar.get_x() + bar.get_width()/2., height + 0.5,
                f'{value:.1f}%', ha='center', va='bottom', fontsize=9, weight='bold')
    
    plt.suptitle('C区技术与知识共享综合分析 (Zone III: Learning Zone)\nTechnology & Knowledge Sharing Analysis',
                 fontsize=16, weight='bold', y=0.995)
    
    output_path = 'C区_技术知识综合分析_完整版.png'
    plt.savefig(output_path, dpi=300, bbox_inches='tight', facecolor='white')
    print(f"✓ Combined chart saved: {output_path}")
    
    return fig


# ============================================================================
# Main Execution
# ============================================================================

def main():
    print("\n" + "="*80)
    print("STRATEGY C FOCUSED VISUALIZER - Technology & Knowledge Sharing Analysis")
    print("="*80 + "\n")
    
    # Load data
    print("📁 Loading data files...")
    budget_df, tech_db, knowledge_db, summary_df = load_data()
    
    if budget_df is None:
        return
    
    print(f"\n📊 Data loaded:")
    print(f"  - {len(budget_df)} budget allocations")
    print(f"  - {len(tech_db)} technologies")
    print(f"  - {len(knowledge_db)} knowledge initiatives")
    print(f"  - {len(summary_df)} summary records")
    
    # Generate individual visualizations
    print("\n📈 Generating focused visualizations...\n")
    
    print("1️⃣  Creating technology effectiveness chart...")
    fig1 = plot_technology_effectiveness(tech_db)
    
    print("2️⃣  Creating knowledge transfer vs reduction chart...")
    fig2 = plot_knowledge_transfer_vs_reduction(budget_df)
    
    print("3️⃣  Creating knowledge initiative impact chart...")
    fig3 = plot_knowledge_initiative_impact(knowledge_db)
    
    print("4️⃣  Creating initiatives vs success rate chart...")
    fig4 = plot_initiatives_vs_success_rate(budget_df, summary_df)
    
    print("\n5️⃣  Creating combined chart with all 4 visualizations...")
    fig_combined = plot_all_combined(budget_df, tech_db, knowledge_db, summary_df)
    
    print("\n" + "="*80)
    print("✅ All focused visualizations generated successfully!")
    print("="*80)
    
    # Calculate and display summary statistics
    print("\n📊 SUMMARY STATISTICS:")
    print(f"  Total Suppliers: {len(summary_df)}")
    print(f"  Success Rate: {(summary_df['是否达标'] == '是').sum() / len(summary_df) * 100:.1f}%")
    print(f"  Average Reduction Rate: {budget_df['减排率'].mean():.2f}%")
    print(f"  Average Knowledge Multiplier: {budget_df['知识倍增器'].mean():.2f}x")
    print(f"  Average Network Effect: {budget_df['网络效应'].mean():.2f}")
    print(f"  Total Investment: ${budget_df['总投资'].sum():,.0f}")
    
    # Technology insights
    print(f"\n🔧 TECHNOLOGY INSIGHTS:")
    top_tech = tech_db.nlargest(3, '减排率')
    print(f"  Top 3 Most Effective Technologies:")
    for idx, tech in top_tech.iterrows():
        print(f"    • {tech['技术名称']}: {tech['减排率']*100:.1f}% reduction")
    
    # Knowledge initiative insights
    print(f"\n🧠 KNOWLEDGE INITIATIVE INSIGHTS:")
    top_initiative = knowledge_db.nlargest(1, '知识倍增器')
    print(f"  Highest Knowledge Multiplier:")
    print(f"    • {top_initiative.iloc[0]['倡议名称']}: {top_initiative.iloc[0]['知识倍增器']:.2f}x")
    
    top_network = knowledge_db.nlargest(1, '网络效应')
    print(f"  Highest Network Effect:")
    print(f"    • {top_network.iloc[0]['倡议名称']}: {top_network.iloc[0]['网络效应']:.2f}")
    
    plt.show()
    
    print("\n✨ Visualization complete! Charts have been saved to the current directory.")


if __name__ == "__main__":
    main()
