"""
Strategy C Visualizer - ESG Supply Chain Analysis
===================================================
This visualizer creates comprehensive charts for Strategy C (Zone III - Learning Zone)
using the exported CSV data from the ML simulation.

Zone III Focus: Low-emission, high-cooperation suppliers
- Knowledge sharing and innovation
- Best practice dissemination
- Network effects and learning
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib import rcParams
import numpy as np
import os

# Chinese font configuration
rcParams['font.sans-serif'] = ['SimHei', 'Arial Unicode MS', 'PingFang SC', 'STHeiti']
rcParams['axes.unicode_minus'] = False

# ============================================================================
# Data Loading
# ============================================================================

def load_data():
    """Load all CSV files generated by the ML simulation"""
    
    try:
        pathway_df = pd.read_csv('ML_simulation_C_三年减排路径.csv', encoding='utf-8-sig')
        classification_df = pd.read_csv('ML_simulation_C_四象限分类.csv', encoding='utf-8-sig')
        budget_df = pd.read_csv('ML_simulation_C_投资预算分配.csv', encoding='utf-8-sig')
        tech_db = pd.read_csv('ML_simulation_C_技术数据库.csv', encoding='utf-8-sig')
        knowledge_db = pd.read_csv('ML_simulation_C_知识共享数据库.csv', encoding='utf-8-sig')
        summary_df = pd.read_csv('ML_simulation_C_strategy_summary.csv', encoding='utf-8-sig')
        
        print("✓ All data files loaded successfully")
        return pathway_df, classification_df, budget_df, tech_db, knowledge_db, summary_df
        
    except FileNotFoundError as e:
        print(f"❌ Error: Could not find data file: {e}")
        print("Please run C_strategy_ML_simulation.py first to generate the data files.")
        return None, None, None, None, None, None


# ============================================================================
# Chart 1: Knowledge Transfer & Cooperation Improvement
# ============================================================================

def plot_knowledge_transfer_analysis(budget_df, classification_df):
    """Analyze knowledge transfer effectiveness and cooperation patterns"""
    
    fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(16, 12))
    
    # Merge data
    merged_df = pd.merge(budget_df, classification_df, on='供应商')
    
    # Chart 1.1: Knowledge Multiplier vs Network Effect
    scatter1 = ax1.scatter(merged_df['知识倍增器'], 
                          merged_df['网络效应'],
                          s=merged_df['预期减排量'] * 2,
                          c=merged_df['创新潜力'],
                          cmap='YlGn',
                          alpha=0.6,
                          edgecolors='black',
                          linewidth=1)
    
    ax1.set_xlabel('知识倍增器 (Knowledge Multiplier)', fontsize=12, weight='bold')
    ax1.set_ylabel('网络效应 (Network Effect)', fontsize=12, weight='bold')
    ax1.set_title('知识转移效能分析\nKnowledge Transfer Effectiveness', 
                  fontsize=14, weight='bold', pad=15)
    ax1.grid(True, alpha=0.3, linestyle='--')
    
    cbar1 = plt.colorbar(scatter1, ax=ax1)
    cbar1.set_label('创新潜力', fontsize=10, weight='bold')
    
    # Chart 1.2: Investment Distribution (Tech vs Knowledge)
    suppliers_top10 = budget_df.nlargest(10, '预期减排量')['供应商']
    top10_data = budget_df[budget_df['供应商'].isin(suppliers_top10)]
    
    x_pos = np.arange(len(top10_data))
    width = 0.35
    
    bars1 = ax2.bar(x_pos - width/2, top10_data['技术投资'], width, 
                    label='技术投资', color='steelblue', alpha=0.8, edgecolor='black')
    bars2 = ax2.bar(x_pos + width/2, top10_data['知识投资'], width,
                    label='知识投资', color='orange', alpha=0.8, edgecolor='black')
    
    ax2.set_xlabel('供应商', fontsize=12, weight='bold')
    ax2.set_ylabel('投资金额 (USD)', fontsize=12, weight='bold')
    ax2.set_title('Top 10 供应商投资分配\nInvestment Distribution', 
                  fontsize=14, weight='bold', pad=15)
    ax2.set_xticks(x_pos)
    ax2.set_xticklabels([s.split('_')[-1] for s in top10_data['供应商']], 
                        rotation=45, ha='right')
    ax2.legend(fontsize=10)
    ax2.grid(True, alpha=0.3, axis='y')
    
    # Chart 1.3: Innovation Potential Distribution
    innovation_bins = [0, 0.3, 0.5, 0.7, 0.9, 1.0]
    innovation_labels = ['很低', '低', '中', '高', '很高']
    merged_df['创新等级'] = pd.cut(merged_df['创新潜力'], 
                                  bins=innovation_bins, 
                                  labels=innovation_labels)
    
    innovation_counts = merged_df['创新等级'].value_counts().sort_index()
    colors_innovation = ['#d62728', '#ff7f0e', '#ffdd57', '#2ca02c', '#1f77b4']
    
    wedges, texts, autotexts = ax3.pie(innovation_counts.values,
                                        labels=innovation_counts.index,
                                        colors=colors_innovation,
                                        autopct='%1.1f%%',
                                        startangle=90,
                                        explode=[0.05] * len(innovation_counts))
    
    for autotext in autotexts:
        autotext.set_color('white')
        autotext.set_weight('bold')
        autotext.set_fontsize(11)
    
    ax3.set_title('创新潜力分布\nInnovation Potential Distribution', 
                  fontsize=14, weight='bold', pad=15)
    
    # Chart 1.4: Knowledge Transfer Score vs Reduction Rate
    scatter2 = ax4.scatter(merged_df['知识转移得分'],
                          merged_df['减排率'],
                          s=merged_df['总投资'] * 0.3,
                          c=merged_df['配合程度'],
                          cmap='plasma',
                          alpha=0.6,
                          edgecolors='black',
                          linewidth=1)
    
    ax4.set_xlabel('知识转移得分 (Knowledge Transfer Score)', fontsize=12, weight='bold')
    ax4.set_ylabel('减排率 (%)', fontsize=12, weight='bold')
    ax4.set_title('知识转移与减排效果\nKnowledge Transfer vs Reduction', 
                  fontsize=14, weight='bold', pad=15)
    ax4.grid(True, alpha=0.3, linestyle='--')
    
    cbar2 = plt.colorbar(scatter2, ax=ax4)
    cbar2.set_label('配合程度', fontsize=10, weight='bold')
    
    plt.suptitle('C区知识转移与配合度综合分析 (Zone III: Learning Zone)\nKnowledge Transfer & Cooperation Analysis', 
                 fontsize=16, weight='bold', y=0.98)
    plt.tight_layout()
    
    output_path = 'C区知识转移综合分析_ML_data.png'
    plt.savefig(output_path, dpi=300, bbox_inches='tight', facecolor='white')
    print(f"✓ Chart saved: {output_path}")
    
    return fig


# ============================================================================
# Chart 2: Investment ROI & Network Effects Analysis
# ============================================================================

def plot_investment_roi_analysis(budget_df, summary_df):
    """Analyze investment ROI and network effects for Zone III"""
    
    fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(16, 12))
    
    # Merge data
    merged_df = pd.merge(budget_df, summary_df, on='供应商')
    
    # Chart 2.1: Top 10 suppliers by ROI
    top10_roi = merged_df.nlargest(10, '投资回报率')
    
    colors_roi = plt.cm.RdYlGn(np.linspace(0.3, 0.9, len(top10_roi)))
    bars = ax1.barh(range(len(top10_roi)), top10_roi['投资回报率'],
                    color=colors_roi, alpha=0.8, edgecolor='black', linewidth=1.5)
    
    ax1.set_yticks(range(len(top10_roi)))
    ax1.set_yticklabels([s.split('_')[-1] for s in top10_roi['供应商']])
    ax1.set_xlabel('投资回报率 (%)', fontsize=12, weight='bold')
    ax1.set_ylabel('供应商', fontsize=12, weight='bold')
    ax1.set_title('Top 10 投资回报率排名\nTop 10 ROI Ranking', 
                  fontsize=14, weight='bold', pad=15)
    ax1.grid(True, alpha=0.3, axis='x')
    
    # Add value labels
    for i, (bar, value) in enumerate(zip(bars, top10_roi['投资回报率'])):
        ax1.text(value + 1, i, f'{value:.1f}%', 
                va='center', ha='left', fontsize=9, weight='bold')
    
    # Chart 2.2: Network Effect Impact
    # Use _x suffix for columns from budget_df (first dataframe in merge)
    network_col = '网络效应_x' if '网络效应_x' in merged_df.columns else '网络效应'
    knowledge_col = '知识倍增器_x' if '知识倍增器_x' in merged_df.columns else '知识倍增器'
    investment_col = '总投资_x' if '总投资_x' in merged_df.columns else '总投资'
    
    scatter1 = ax2.scatter(merged_df[network_col],
                          merged_df['减排量'],
                          s=merged_df[investment_col] * 0.5,
                          c=merged_df[knowledge_col],
                          cmap='viridis',
                          alpha=0.6,
                          edgecolors='black',
                          linewidth=1)
    
    ax2.set_xlabel('网络效应 (Network Effect)', fontsize=12, weight='bold')
    ax2.set_ylabel('减排量 (tons CO₂)', fontsize=12, weight='bold')
    ax2.set_title('网络效应对减排的影响\nNetwork Effect Impact on Reduction', 
                  fontsize=14, weight='bold', pad=15)
    ax2.grid(True, alpha=0.3, linestyle='--')
    
    cbar1 = plt.colorbar(scatter1, ax=ax2)
    cbar1.set_label('知识倍增器', fontsize=10, weight='bold')
    
    # Chart 2.3: Payback Period Distribution
    valid_payback = merged_df[merged_df['回本周期(年)'] < 20]  # Filter outliers
    
    ax3.hist(valid_payback['回本周期(年)'], bins=15, color='teal', 
            alpha=0.7, edgecolor='black', linewidth=1.5)
    
    mean_payback = valid_payback['回本周期(年)'].mean()
    ax3.axvline(mean_payback, color='red', linestyle='--', linewidth=2.5,
               label=f'平均: {mean_payback:.1f}年')
    
    ax3.set_xlabel('回本周期 (年)', fontsize=12, weight='bold')
    ax3.set_ylabel('供应商数量', fontsize=12, weight='bold')
    ax3.set_title('投资回本周期分布\nPayback Period Distribution', 
                  fontsize=14, weight='bold', pad=15)
    ax3.legend(fontsize=11)
    ax3.grid(True, alpha=0.3, axis='y')
    
    # Chart 2.4: Cost-Effectiveness Analysis
    investment_col = '总投资_x' if '总投资_x' in merged_df.columns else '总投资'
    merged_df['成本效益'] = merged_df['减排量'] / merged_df[investment_col]
    top8_efficiency = merged_df.nlargest(8, '成本效益')
    
    x_pos = np.arange(len(top8_efficiency))
    bars2 = ax4.bar(x_pos, top8_efficiency['成本效益'],
                   color='seagreen', alpha=0.8, edgecolor='black', linewidth=1.5)
    
    ax4.set_xticks(x_pos)
    ax4.set_xticklabels([s.split('_')[-1] for s in top8_efficiency['供应商']],
                       rotation=45, ha='right')
    ax4.set_xlabel('供应商', fontsize=12, weight='bold')
    ax4.set_ylabel('成本效益 (tons CO₂ / USD)', fontsize=12, weight='bold')
    ax4.set_title('Top 8 成本效益分析\nTop 8 Cost-Effectiveness', 
                  fontsize=14, weight='bold', pad=15)
    ax4.grid(True, alpha=0.3, axis='y')
    
    # Add value labels
    for i, (bar, value) in enumerate(zip(bars2, top8_efficiency['成本效益'])):
        ax4.text(i, value + 0.001, f'{value:.4f}',
                ha='center', va='bottom', fontsize=9, weight='bold')
    
    plt.suptitle('C区投资回报与网络效应分析 (Zone III: Learning Zone)\nInvestment ROI & Network Effects', 
                 fontsize=16, weight='bold', y=0.98)
    plt.tight_layout()
    
    output_path = 'C区投资回报与网络效应分析_ML_data.png'
    plt.savefig(output_path, dpi=300, bbox_inches='tight', facecolor='white')
    print(f"✓ Chart saved: {output_path}")
    
    return fig


# ============================================================================
# Chart 3: Three-Year Emission Pathway (Top 8)
# ============================================================================

def plot_emission_pathway(pathway_df, summary_df):
    """Plot three-year emission reduction pathways for top 8 suppliers"""
    
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(18, 7))
    
    # Get top 8 suppliers by total reduction
    top8_suppliers = summary_df.nlargest(8, '减排量')['供应商'].tolist()
    
    # Chart 3.1: Emission pathways
    colors = plt.cm.viridis(np.linspace(0.1, 0.9, 8))
    year_mapping = {'基线年': 0, '第1年': 1, '第2年': 2, '第3年': 3}
    
    for idx, supplier in enumerate(top8_suppliers):
        supplier_data = pathway_df[pathway_df['供应商'] == supplier].copy()
        supplier_data['年份数值'] = supplier_data['年份'].map(year_mapping)
        supplier_data = supplier_data.sort_values('年份数值')
        
        ax1.plot(supplier_data['年份数值'], supplier_data['碳排放(吨CO2)'],
                marker='o', linewidth=2.5, markersize=8, color=colors[idx],
                label=supplier.split('_')[-1], alpha=0.8)
    
    ax1.set_xticks([0, 1, 2, 3])
    ax1.set_xticklabels(['基线年', '第1年', '第2年', '第3年'])
    ax1.set_xlabel('年份', fontsize=12, weight='bold')
    ax1.set_ylabel('碳排放量 (tons CO₂)', fontsize=12, weight='bold')
    ax1.set_title('Top 8 供应商三年减排路径\nTop 8 Three-Year Emission Pathway',
                  fontsize=14, weight='bold', pad=15)
    ax1.legend(loc='upper right', fontsize=9, ncol=2)
    ax1.grid(True, alpha=0.3, linestyle='--')
    
    # Chart 3.2: Cumulative reduction
    for idx, supplier in enumerate(top8_suppliers):
        supplier_data = pathway_df[pathway_df['供应商'] == supplier].copy()
        supplier_data['年份数值'] = supplier_data['年份'].map(year_mapping)
        supplier_data = supplier_data.sort_values('年份数值')
        
        ax2.plot(supplier_data['年份数值'], supplier_data['累计减排量(吨CO2)'],
                marker='s', linewidth=2.5, markersize=8, color=colors[idx],
                label=supplier.split('_')[-1], alpha=0.8)
    
    ax2.set_xticks([0, 1, 2, 3])
    ax2.set_xticklabels(['基线年', '第1年', '第2年', '第3年'])
    ax2.set_xlabel('年份', fontsize=12, weight='bold')
    ax2.set_ylabel('累计减排量 (tons CO₂)', fontsize=12, weight='bold')
    ax2.set_title('Top 8 供应商累计减排量\nTop 8 Cumulative Reduction',
                  fontsize=14, weight='bold', pad=15)
    ax2.legend(loc='upper left', fontsize=9, ncol=2)
    ax2.grid(True, alpha=0.3, linestyle='--')
    
    plt.suptitle('C区三年减排路径分析 (Zone III: Learning Zone)\nThree-Year Emission Reduction Pathway',
                 fontsize=16, weight='bold', y=1.00)
    plt.tight_layout()
    
    output_path = 'C区三年减排路径_Top8_ML_data.png'
    plt.savefig(output_path, dpi=300, bbox_inches='tight', facecolor='white')
    print(f"✓ Chart saved: {output_path}")
    
    return fig


# ============================================================================
# Chart 4: Technology & Knowledge Initiative Analysis
# ============================================================================

def plot_technology_knowledge_analysis(tech_db, knowledge_db, summary_df, budget_df):
    """Analyze technology adoption and knowledge initiatives"""
    
    fig = plt.figure(figsize=(18, 10))
    gs = fig.add_gridspec(2, 3, hspace=0.3, wspace=0.3)
    
    # Chart 4.1: Technology Effectiveness
    ax1 = fig.add_subplot(gs[0, 0])
    
    if '技术名称' in tech_db.columns:
        tech_db_sorted = tech_db.sort_values('减排率', ascending=True)
        
        colors_tech = plt.cm.RdYlGn(np.linspace(0.3, 0.9, len(tech_db_sorted)))
        bars = ax1.barh(range(len(tech_db_sorted)), tech_db_sorted['减排率'] * 100,
                       color=colors_tech, alpha=0.8, edgecolor='black', linewidth=1)
        
        ax1.set_yticks(range(len(tech_db_sorted)))
        ax1.set_yticklabels(tech_db_sorted['技术名称'], fontsize=8)
        ax1.set_xlabel('减排率 (%)', fontsize=11, weight='bold')
        ax1.set_title('技术减排效果\nTechnology Effectiveness', fontsize=12, weight='bold')
        ax1.grid(True, alpha=0.3, axis='x')
    
    # Chart 4.2: Knowledge Transfer Value
    ax2 = fig.add_subplot(gs[0, 1])
    
    if '知识转移价值' in tech_db.columns:
        scatter = ax2.scatter(tech_db['单位成本'] / 1000, 
                             tech_db['知识转移价值'],
                             s=tech_db['减排率'] * 1000,
                             c=tech_db['年度运营节省'],
                             cmap='coolwarm',
                             alpha=0.6,
                             edgecolors='black',
                             linewidth=1)
        
        ax2.set_xlabel('单位成本 (千USD)', fontsize=11, weight='bold')
        ax2.set_ylabel('知识转移价值', fontsize=11, weight='bold')
        ax2.set_title('技术成本 vs 知识价值\nCost vs Knowledge Value', fontsize=12, weight='bold')
        ax2.grid(True, alpha=0.3)
        
        cbar = plt.colorbar(scatter, ax=ax2)
        cbar.set_label('年度节省', fontsize=9)
    
    # Chart 4.3: Knowledge Initiative Impact
    ax3 = fig.add_subplot(gs[0, 2])
    
    if '倡议名称' in knowledge_db.columns:
        x_pos = np.arange(len(knowledge_db))
        width = 0.35
        
        bars1 = ax3.bar(x_pos - width/2, knowledge_db['知识倍增器'],
                       width, label='知识倍增器', color='steelblue', alpha=0.8)
        bars2 = ax3.bar(x_pos + width/2, knowledge_db['网络效应'],
                       width, label='网络效应', color='orange', alpha=0.8)
        
        ax3.set_xticks(x_pos)
        ax3.set_xticklabels(knowledge_db['倡议名称'], rotation=45, ha='right', fontsize=8)
        ax3.set_ylabel('效果值', fontsize=11, weight='bold')
        ax3.set_title('知识共享倡议效果\nKnowledge Initiative Impact', fontsize=12, weight='bold')
        ax3.legend(fontsize=9)
        ax3.grid(True, alpha=0.3, axis='y')
    
    # Chart 4.4: Technology vs Knowledge Investment
    ax4 = fig.add_subplot(gs[1, 0])
    
    tech_total = budget_df['技术投资'].sum()
    knowledge_total = budget_df['知识投资'].sum()
    
    sizes = [tech_total, knowledge_total]
    labels = [f'技术投资\n${tech_total:,.0f}', f'知识投资\n${knowledge_total:,.0f}']
    colors_pie = ['steelblue', 'orange']
    explode = (0.05, 0.05)
    
    wedges, texts, autotexts = ax4.pie(sizes, labels=labels, colors=colors_pie,
                                        autopct='%1.1f%%', startangle=90,
                                        explode=explode)
    
    for autotext in autotexts:
        autotext.set_color('white')
        autotext.set_weight('bold')
        autotext.set_fontsize(12)
    
    ax4.set_title('投资分配比例\nInvestment Distribution', fontsize=12, weight='bold')
    
    # Chart 4.5: Success Rate by Initiative Count
    ax5 = fig.add_subplot(gs[1, 1])
    
    merged_data = pd.merge(budget_df, summary_df, on='供应商')
    initiative_success = merged_data.groupby('知识倡议数')['是否达标'].apply(
        lambda x: (x == '是').sum() / len(x) * 100
    ).reset_index()
    
    bars = ax5.bar(initiative_success['知识倡议数'], 
                   initiative_success['是否达标'],
                   color='seagreen', alpha=0.8, edgecolor='black', linewidth=1.5)
    
    ax5.set_xlabel('知识倡议数量', fontsize=11, weight='bold')
    ax5.set_ylabel('达标率 (%)', fontsize=11, weight='bold')
    ax5.set_title('倡议数量与成功率\nInitiatives vs Success Rate', fontsize=12, weight='bold')
    ax5.grid(True, alpha=0.3, axis='y')
    
    for bar in bars:
        height = bar.get_height()
        ax5.text(bar.get_x() + bar.get_width()/2., height,
                f'{height:.1f}%', ha='center', va='bottom', fontsize=10, weight='bold')
    
    # Chart 4.6: Overall Statistics
    ax6 = fig.add_subplot(gs[1, 2])
    ax6.axis('off')
    
    total_suppliers = len(summary_df)
    success_count = (summary_df['是否达标'] == '是').sum()
    success_rate = success_count / total_suppliers * 100
    avg_reduction = summary_df['减排量'].mean()
    avg_reduction_rate = summary_df['减排率'].mean()
    avg_knowledge_multiplier = budget_df['知识倍增器'].mean()
    
    stats_text = f"""
╔════════════════════════════╗
║  C区 统计摘要 (Zone III)  ║
╚════════════════════════════╝

📊 供应商总数: {total_suppliers}

✅ 达标情况:
  • 达标数: {success_count}
  • 达标率: {success_rate:.1f}%

📉 减排效果:
  • 平均减排: {avg_reduction:.0f} tons
  • 平均减排率: {avg_reduction_rate:.1f}%

🧠 知识转移:
  • 平均倍增器: {avg_knowledge_multiplier:.2f}x

💰 投资效率:
  • 技术投资: ${tech_total:,.0f}
  • 知识投资: ${knowledge_total:,.0f}
  • 总计: ${tech_total + knowledge_total:,.0f}
    """
    
    ax6.text(0.1, 0.5, stats_text, fontsize=10, family='monospace',
            verticalalignment='center',
            bbox=dict(boxstyle='round', facecolor='lightblue', alpha=0.3))
    
    plt.suptitle('C区技术与知识倡议综合分析 (Zone III: Learning Zone)\nTechnology & Knowledge Initiative Analysis',
                 fontsize=16, weight='bold', y=0.98)
    
    output_path = 'C区技术知识综合分析_ML_data.png'
    plt.savefig(output_path, dpi=300, bbox_inches='tight', facecolor='white')
    print(f"✓ Chart saved: {output_path}")
    
    return fig


# ============================================================================
# Main Execution
# ============================================================================

def main():
    print("\n" + "="*80)
    print("STRATEGY C VISUALIZER - Zone III (Learning Zone) Data Analysis")
    print("="*80 + "\n")
    
    # Load data
    print("📁 Loading data files...")
    pathway_df, classification_df, budget_df, tech_db, knowledge_db, summary_df = load_data()
    
    if pathway_df is None:
        return
    
    print(f"\n📊 Data loaded:")
    print(f"  - {len(pathway_df)} pathway records")
    print(f"  - {len(classification_df)} supplier classifications")
    print(f"  - {len(budget_df)} budget allocations")
    print(f"  - {len(tech_db)} technologies")
    print(f"  - {len(knowledge_db)} knowledge initiatives")
    print(f"  - {len(summary_df)} summary records")
    
    # Generate visualizations
    print("\n📈 Generating visualizations...\n")
    
    print("1️⃣  Creating knowledge transfer & cooperation analysis...")
    fig1 = plot_knowledge_transfer_analysis(budget_df, classification_df)
    
    print("2️⃣  Creating investment ROI & network effects analysis...")
    fig2 = plot_investment_roi_analysis(budget_df, summary_df)
    
    print("3️⃣  Creating three-year emission pathway...")
    fig3 = plot_emission_pathway(pathway_df, summary_df)
    
    print("4️⃣  Creating technology & knowledge initiative analysis...")
    fig4 = plot_technology_knowledge_analysis(tech_db, knowledge_db, summary_df, budget_df)
    
    print("\n" + "="*80)
    print("✅ All visualizations generated successfully!")
    print("="*80)
    
    # Calculate and display summary statistics
    print("\n📊 SUMMARY STATISTICS:")
    print(f"  Total Suppliers: {len(summary_df)}")
    print(f"  Total Baseline Emissions: {classification_df['年碳排放(吨CO2)'].sum():,.0f} tons CO₂")
    print(f"  Total Reduction: {summary_df['减排量'].sum():,.0f} tons CO₂")
    print(f"  Average Reduction Rate: {summary_df['减排率'].mean():.2f}%")
    print(f"  Success Rate: {(summary_df['是否达标'] == '是').sum() / len(summary_df) * 100:.1f}%")
    print(f"  Total Investment: ${budget_df['总投资'].sum():,.0f}")
    print(f"  Average Knowledge Multiplier: {budget_df['知识倍增器'].mean():.2f}x")
    print(f"  Average Network Effect: {budget_df['网络效应'].mean():.2f}")
    print(f"  Average Innovation Potential: {budget_df['创新潜力'].mean():.2f}")
    
    plt.show()
    
    print("\n✨ Visualization complete! Charts have been saved to the current directory.")


if __name__ == "__main__":
    main()
