"""
Strategy D Visualizer - ESG Supply Chain Emission Reduction
============================================================
This script creates detailed visualizations for Strategy D (Zone IV - Observation Zone)
using the data generated by D_strategy_ML_simulation.py

Focus: Low-emission, low-cooperation suppliers
- Basic management approach with minimal investment
- Automated monitoring and simplified requirements
- Cost-effective technologies with quick payback
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import rcParams
import seaborn as sns
import os

# Chinese font configuration
rcParams['font.sans-serif'] = ['SimHei', 'Arial Unicode MS', 'PingFang SC', 'STHeiti']
rcParams['axes.unicode_minus'] = False

# Set style
sns.set_palette("husl")

# File paths
pathway_file = 'ML_simulation_D_三年减排路径.csv'
classification_file = 'ML_simulation_D_四象限分类.csv'
budget_file = 'ML_simulation_D_投资预算分配.csv'
tech_file = 'ML_simulation_D_技术数据库.csv'
management_file = 'ML_simulation_D_基础管理数据库.csv'
supplier_file = 'ML_simulation_D_供应商详细信息.csv'
summary_file = 'ML_simulation_D_strategy_summary.csv'

# Check if files exist
files_to_check = [pathway_file, classification_file, budget_file, tech_file, 
                  management_file, supplier_file, summary_file]

missing_files = [f for f in files_to_check if not os.path.exists(f)]

if missing_files:
    print("\n⚠️  Missing data files. Please run D_strategy_ML_simulation.py first!")
    print(f"Missing: {', '.join(missing_files)}")
    exit(1)

# Load data
print("\n📊 Loading Strategy D data files...")
df_pathway = pd.read_csv(pathway_file)
df_classification = pd.read_csv(classification_file)
df_budget = pd.read_csv(budget_file)
df_tech = pd.read_csv(tech_file)
df_management = pd.read_csv(management_file)
df_supplier = pd.read_csv(supplier_file)
df_summary = pd.read_csv(summary_file)

print(f"✓ Loaded {len(df_supplier)} suppliers")
print(f"✓ Loaded {len(df_tech)} technologies")
print(f"✓ Loaded {len(df_management)} management initiatives")

# ============================================================================
# Create Comprehensive Visualization
# ============================================================================

fig = plt.figure(figsize=(24, 16))
gs = fig.add_gridspec(4, 4, hspace=0.35, wspace=0.35)

# Color scheme for Zone IV
zone_color = '#95A5A6'  # Gray
accent_color = '#34495E'  # Dark gray
success_color = '#27AE60'  # Green
warning_color = '#E67E22'  # Orange
danger_color = '#E74C3C'  # Red

# ============================================================================
# 1. Three-Year Reduction Pathway (Top Left, Large)
# ============================================================================
ax1 = fig.add_subplot(gs[0:2, 0])

# Select top 20 suppliers by baseline emission
top_suppliers = df_summary.nlargest(20, '基线排放')['供应商ID'].tolist()

for supplier_id in top_suppliers:
    supplier_data = df_pathway[df_pathway['供应商ID'] == supplier_id]
    if len(supplier_data) > 0:
        years = [0, 1, 2, 3]
        emissions = supplier_data['碳排放量'].tolist()
        ax1.plot(years, emissions, marker='o', alpha=0.5, linewidth=2)

ax1.set_xlabel('年份 (Year)', fontsize=13, weight='bold')
ax1.set_ylabel('碳排放量 (吨 CO₂e)', fontsize=13, weight='bold')
ax1.set_title('D区供应商三年减排路径 (Top 20)\nZone IV 3-Year Emission Reduction Pathway', 
             fontsize=14, weight='bold', pad=10)
ax1.grid(True, alpha=0.3, linestyle='--')
ax1.set_xticks([0, 1, 2, 3])
ax1.set_xticklabels(['基线\nBaseline', '第1年\nYear 1', '第2年\nYear 2', '第3年\nYear 3'])

# Add average line
avg_by_year = df_pathway.groupby('年份')['碳排放量'].mean()
years_avg = [0, 1, 2, 3]
avg_emissions = [avg_by_year[f'Y{i}'] for i in range(4)]
ax1.plot(years_avg, avg_emissions, marker='s', linewidth=4, color='red', 
         label='平均值 (Average)', linestyle='--', markersize=10)
ax1.legend(fontsize=11)

# ============================================================================
# 2. Reduction Rate Distribution (Top Middle)
# ============================================================================
ax2 = fig.add_subplot(gs[0, 1])

reduction_rates = df_summary['减排率'].values
# Use bar chart to avoid bin issues
from collections import Counter
rate_counts = Counter([round(r, 1) for r in reduction_rates])
rates_sorted = sorted(rate_counts.keys())
counts = [rate_counts[r] for r in rates_sorted]
ax2.bar(range(len(rates_sorted)), counts, color=zone_color, edgecolor='black', alpha=0.7)
ax2.set_xticks(range(0, len(rates_sorted), max(1, len(rates_sorted)//8)))
ax2.set_xticklabels([f'{rates_sorted[i]:.1f}' for i in range(0, len(rates_sorted), max(1, len(rates_sorted)//8))], rotation=45)
ax2.axvline(reduction_rates.mean(), color='red', linestyle='--', 
           linewidth=2.5, label=f'平均: {reduction_rates.mean():.1f}%')
ax2.axvline(5, color='orange', linestyle=':', linewidth=2, label='最低目标: 5%')
ax2.axvline(10, color='green', linestyle=':', linewidth=2, label='最高目标: 10%')

ax2.set_xlabel('减排率 (%)', fontsize=12, weight='bold')
ax2.set_ylabel('供应商数量', fontsize=12, weight='bold')
ax2.set_title('减排率分布\nReduction Rate Distribution', fontsize=13, weight='bold')
ax2.legend(fontsize=9)
ax2.grid(True, alpha=0.3, axis='y')

# ============================================================================
# 3. Investment vs Reduction Analysis (Top Right)
# ============================================================================
ax3 = fig.add_subplot(gs[0, 2])

scatter = ax3.scatter(df_summary['总投资'], df_summary['最终减排量'], 
                     c=df_summary['减排率'], cmap='RdYlGn', 
                     s=120, alpha=0.7, edgecolors='black', linewidth=1.5)
ax3.set_xlabel('总投资 (USD)', fontsize=12, weight='bold')
ax3.set_ylabel('总减排量 (吨 CO₂e)', fontsize=12, weight='bold')
ax3.set_title('投资回报分析\nInvestment vs Reduction', fontsize=13, weight='bold')
cbar = plt.colorbar(scatter, ax=ax3)
cbar.set_label('减排率 (%)', fontsize=10)
ax3.grid(True, alpha=0.3)

# Add trend line
z = np.polyfit(df_summary['总投资'], df_summary['最终减排量'], 1)
p = np.poly1d(z)
ax3.plot(df_summary['总投资'].sort_values(), 
        p(df_summary['总投资'].sort_values()), 
        "r--", linewidth=2, alpha=0.8, label='趋势线')
ax3.legend(fontsize=9)

# ============================================================================
# 4. Efficiency Distribution (Top Far Right)
# ============================================================================
ax4 = fig.add_subplot(gs[0, 3])

efficiency = df_summary['效率(吨/美元)'].values
ax4.hist(efficiency, bins=20, color=accent_color, edgecolor='black', alpha=0.7)
ax4.axvline(efficiency.mean(), color='red', linestyle='--', 
           linewidth=2.5, label=f'平均: {efficiency.mean():.4f}')

ax4.set_xlabel('效率 (吨 CO₂e / USD)', fontsize=12, weight='bold')
ax4.set_ylabel('供应商数量', fontsize=12, weight='bold')
ax4.set_title('减排效率分布\nEfficiency Distribution', fontsize=13, weight='bold')
ax4.legend(fontsize=9)
ax4.grid(True, alpha=0.3, axis='y')

# ============================================================================
# 5. Technology Adoption Ranking (Middle Left)
# ============================================================================
ax5 = fig.add_subplot(gs[1, 1])

# Count technology adoptions
tech_counter = {}
for tech_list in df_budget['已选技术'].dropna():
    techs = [t.strip() for t in tech_list.split(',')]
    for tech in techs:
        if tech:
            tech_short = tech.split('(')[0].strip()
            tech_counter[tech_short] = tech_counter.get(tech_short, 0) + 1

top_techs = sorted(tech_counter.items(), key=lambda x: x[1], reverse=True)[:10]
tech_names = [t[0] for t in top_techs]
tech_counts = [t[1] for t in top_techs]

colors_tech = [zone_color if i % 2 == 0 else accent_color for i in range(len(tech_names))]
bars = ax5.barh(tech_names, tech_counts, color=colors_tech, edgecolor='black')

ax5.set_xlabel('采用次数', fontsize=12, weight='bold')
ax5.set_title('热门技术采用排名 (Top 10)\nTop Technologies Adopted', 
             fontsize=13, weight='bold')
ax5.grid(True, alpha=0.3, axis='x')

for i, bar in enumerate(bars):
    width = bar.get_width()
    ax5.text(width, bar.get_y() + bar.get_height()/2., f'{int(width)}',
            ha='left', va='center', fontsize=9, weight='bold', 
            bbox=dict(boxstyle='round,pad=0.3', facecolor='yellow', alpha=0.3))

# ============================================================================
# 6. Payback Period Distribution (Middle Middle)
# ============================================================================
ax6 = fig.add_subplot(gs[1, 2])

payback = df_budget['投资回收期'].values
# Use bar chart to avoid bin issues  
from collections import Counter
payback_counts = Counter([round(p, 1) for p in payback])
paybacks_sorted = sorted(payback_counts.keys())
counts_p = [payback_counts[p] for p in paybacks_sorted]
ax6.bar(range(len(paybacks_sorted)), counts_p, color=success_color, edgecolor='black', alpha=0.7)
ax6.set_xticks(range(0, len(paybacks_sorted), max(1, len(paybacks_sorted)//8)))
ax6.set_xticklabels([f'{paybacks_sorted[i]:.1f}' for i in range(0, len(paybacks_sorted), max(1, len(paybacks_sorted)//8))], rotation=45)
ax6.axvline(payback.mean(), color='red', linestyle='--', 
           linewidth=2.5, label=f'平均: {payback.mean():.1f}年')
ax6.axvline(5, color='orange', linestyle=':', linewidth=2, label='目标: <5年')

ax6.set_xlabel('投资回收期 (年)', fontsize=12, weight='bold')
ax6.set_ylabel('供应商数量', fontsize=12, weight='bold')
ax6.set_title('投资回收期分布\nPayback Period Distribution', fontsize=13, weight='bold')
ax6.legend(fontsize=9)
ax6.grid(True, alpha=0.3, axis='y')

# ============================================================================
# 7. Cooperation Factor Impact (Middle Right)
# ============================================================================
ax7 = fig.add_subplot(gs[1, 3])

coop_factors = df_summary['配合度因子'].values
reduction_rates = df_summary['减排率'].values

ax7.scatter(coop_factors, reduction_rates, s=100, alpha=0.6, 
           color=zone_color, edgecolors='black', linewidth=1.5)

# Trend line
z = np.polyfit(coop_factors, reduction_rates, 1)
p = np.poly1d(z)
ax7.plot(sorted(coop_factors), p(sorted(coop_factors)), 
        "r--", linewidth=3, label=f'趋势线 (R² 相关)')

ax7.set_xlabel('配合度因子', fontsize=12, weight='bold')
ax7.set_ylabel('减排率 (%)', fontsize=12, weight='bold')
ax7.set_title('配合度对减排效果的影响\nCooperation Factor Impact', 
             fontsize=13, weight='bold')
ax7.legend(fontsize=9)
ax7.grid(True, alpha=0.3)

# ============================================================================
# 8. Cost Structure Analysis (Bottom Left)
# ============================================================================
ax8 = fig.add_subplot(gs[2, 0])

avg_tech_inv = df_budget['技术投资'].mean()
avg_mgmt_cost = df_budget['管理成本'].mean()

categories = ['技术投资\nTechnology', '管理成本\nManagement']
costs = [avg_tech_inv, avg_mgmt_cost]
colors_bar = [zone_color, accent_color]

bars = ax8.bar(categories, costs, color=colors_bar, edgecolor='black', width=0.5)
ax8.set_ylabel('平均成本 (USD)', fontsize=12, weight='bold')
ax8.set_title('成本结构分析\nCost Breakdown', fontsize=13, weight='bold')
ax8.grid(True, alpha=0.3, axis='y')

for bar in bars:
    height = bar.get_height()
    ax8.text(bar.get_x() + bar.get_width()/2., height,
            f'${height:.0f}', ha='center', va='bottom', 
            fontsize=11, weight='bold',
            bbox=dict(boxstyle='round,pad=0.3', facecolor='yellow', alpha=0.5))

# Add percentage labels
total_cost = sum(costs)
for i, bar in enumerate(bars):
    height = bar.get_height()
    percentage = (height / total_cost) * 100
    ax8.text(bar.get_x() + bar.get_width()/2., height/2,
            f'{percentage:.1f}%', ha='center', va='center', 
            fontsize=12, weight='bold', color='white')

# ============================================================================
# 9. Target Achievement Rate (Bottom Middle Left)
# ============================================================================
ax9 = fig.add_subplot(gs[2, 1])

achieved = df_budget['目标达成'].value_counts()
labels = []
sizes = []
colors_pie = []

if '是' in achieved.index:
    labels.append(f'达标\nAchieved\n({achieved["是"]})')
    sizes.append(achieved['是'])
    colors_pie.append(success_color)

if '否' in achieved.index:
    labels.append(f'未达标\nNot Achieved\n({achieved["否"]})')
    sizes.append(achieved['否'])
    colors_pie.append(danger_color)

explode = tuple([0.05] + [0]*(len(sizes)-1))

wedges, texts, autotexts = ax9.pie(sizes, explode=explode, labels=labels, 
                                     colors=colors_pie, autopct='%1.1f%%', 
                                     startangle=90, textprops={'fontsize': 11, 'weight': 'bold'})

for autotext in autotexts:
    autotext.set_color('white')
    autotext.set_fontsize(13)
    autotext.set_weight('bold')

ax9.set_title('目标达成率\nTarget Achievement Rate', fontsize=13, weight='bold')

# ============================================================================
# 10. Automation Level Impact (Bottom Middle Right)
# ============================================================================
ax10 = fig.add_subplot(gs[2, 2])

automation = df_summary['自动化水平'].values
efficiency = df_summary['效率(吨/美元)'].values

ax10.scatter(automation, efficiency, s=100, alpha=0.6, 
            color=accent_color, edgecolors='black', linewidth=1.5)

# Trend line
z = np.polyfit(automation, efficiency, 1)
p = np.poly1d(z)
ax10.plot(sorted(automation), p(sorted(automation)), 
         "r--", linewidth=3, label='趋势线')

ax10.set_xlabel('自动化水平', fontsize=12, weight='bold')
ax10.set_ylabel('效率 (吨 CO₂e / USD)', fontsize=12, weight='bold')
ax10.set_title('自动化水平对效率的影响\nAutomation Level Impact', 
              fontsize=13, weight='bold')
ax10.legend(fontsize=9)
ax10.grid(True, alpha=0.3)

# ============================================================================
# 11. Supplier Industry Distribution (Bottom Right)
# ============================================================================
ax11 = fig.add_subplot(gs[2, 3])

industry_counts = df_supplier['industry_type'].value_counts()
colors_industry = sns.color_palette("Set3", n_colors=len(industry_counts))

wedges, texts, autotexts = ax11.pie(industry_counts.values, 
                                      labels=industry_counts.index,
                                      colors=colors_industry, 
                                      autopct='%1.1f%%', 
                                      startangle=90,
                                      textprops={'fontsize': 10, 'weight': 'bold'})

for autotext in autotexts:
    autotext.set_color('white')
    autotext.set_fontsize(11)
    autotext.set_weight('bold')

ax11.set_title('供应商行业分布\nSupplier Industry Distribution', 
              fontsize=13, weight='bold')

# ============================================================================
# 12. Monitoring Frequency Analysis (Bottom Far Left)
# ============================================================================
ax12 = fig.add_subplot(gs[3, 0])

monitoring_freq = df_budget['监测频率'].value_counts().sort_index()
freq_labels = [f'{int(f)}次/年' for f in monitoring_freq.index]

bars = ax12.bar(freq_labels, monitoring_freq.values, 
               color=zone_color, edgecolor='black', alpha=0.7)
ax12.set_xlabel('监测频率', fontsize=12, weight='bold')
ax12.set_ylabel('供应商数量', fontsize=12, weight='bold')
ax12.set_title('监测频率分布\nMonitoring Frequency', fontsize=13, weight='bold')
ax12.grid(True, alpha=0.3, axis='y')

for bar in bars:
    height = bar.get_height()
    ax12.text(bar.get_x() + bar.get_width()/2., height,
             f'{int(height)}', ha='center', va='bottom', 
             fontsize=10, weight='bold')

# ============================================================================
# 13. Technology Cost Distribution (Bottom Middle Far Left)
# ============================================================================
ax13 = fig.add_subplot(gs[3, 1])

tech_costs = df_tech['单位成本'].values
# Use bar chart
from collections import Counter
cost_counts = Counter([round(c, -2) for c in tech_costs])  # Round to nearest 100
costs_sorted = sorted(cost_counts.keys())
counts_c = [cost_counts[c] for c in costs_sorted]
ax13.bar(range(len(costs_sorted)), counts_c, color=success_color, edgecolor='black', alpha=0.7)
ax13.set_xticks(range(len(costs_sorted)))
ax13.set_xticklabels([f'${int(costs_sorted[i])}' for i in range(len(costs_sorted))], rotation=45)
ax13.axvline(tech_costs.mean(), color='red', linestyle='--', 
            linewidth=2.5, label=f'平均: ${tech_costs.mean():.0f}')

ax13.set_xlabel('技术成本 (USD)', fontsize=12, weight='bold')
ax13.set_ylabel('技术数量', fontsize=12, weight='bold')
ax13.set_title('技术成本分布\nTechnology Cost Distribution', 
              fontsize=13, weight='bold')
ax13.grid(True, alpha=0.3, axis='y')

# ============================================================================
# 14. Annual Savings Analysis (Bottom Middle Far Right)
# ============================================================================
ax14 = fig.add_subplot(gs[3, 2])

annual_savings = df_budget['年度节省'].values
total_investment = df_budget['总投资'].values

ax14.scatter(total_investment, annual_savings, s=100, alpha=0.6,
            color=success_color, edgecolors='black', linewidth=1.5)

# Trend line
z = np.polyfit(total_investment, annual_savings, 1)
p = np.poly1d(z)
ax14.plot(sorted(total_investment), p(sorted(total_investment)), 
         "r--", linewidth=3, label='趋势线')

ax14.set_xlabel('总投资 (USD)', fontsize=12, weight='bold')
ax14.set_ylabel('年度节省 (USD)', fontsize=12, weight='bold')
ax14.set_title('投资与年度节省关系\nInvestment vs Annual Savings', 
              fontsize=13, weight='bold')
ax14.legend(fontsize=9)
ax14.grid(True, alpha=0.3)

# ============================================================================
# 15. Key Metrics Summary (Bottom Right)
# ============================================================================
ax15 = fig.add_subplot(gs[3, 3])
ax15.axis('off')

total_suppliers = len(df_supplier)
total_baseline = df_summary['基线排放'].sum()
total_reduction = df_summary['最终减排量'].sum()
total_investment = df_summary['总投资'].sum()
avg_efficiency = df_summary['效率(吨/美元)'].mean()
success_rate = (df_budget['目标达成'] == '是').sum() / len(df_budget) * 100
avg_payback = df_budget['投资回收期'].mean()
avg_automation = df_summary['自动化水平'].mean()

summary_text = f"""
{'='*35}
策略D 关键指标汇总
STRATEGY D KEY METRICS
{'='*35}

📊 供应商样本数
   {total_suppliers} 家

🏭 基线总排放
   {total_baseline:,.0f} 吨 CO₂e

✅ 总减排量
   {total_reduction:,.0f} 吨 CO₂e
   ({total_reduction/total_baseline*100:.1f}%)

💰 总投资
   ${total_investment:,.0f} USD

📈 平均效率
   {avg_efficiency:.4f} 吨/美元

🎯 目标达成率
   {success_rate:.1f}%

⏱️  平均回收期
   {avg_payback:.1f} 年

🤖 平均自动化水平
   {avg_automation:.2f}

💡 策略特点
   • 低成本高效率
   • 自动化监测为主
   • 简化管理流程
   • 快速投资回收

{'='*35}
"""

ax15.text(0.05, 0.95, summary_text, transform=ax15.transAxes,
         fontsize=10, verticalalignment='top', family='monospace',
         bbox=dict(boxstyle='round,pad=0.8', facecolor='wheat', 
                  edgecolor='black', linewidth=2, alpha=0.8))

# ============================================================================
# Main Title
# ============================================================================
fig.suptitle('策略D综合分析 - IV区观察区 (低排放×低配合)\nStrategy D Comprehensive Analysis - Zone IV Observation Zone (Low Emission × Low Cooperation)',
            fontsize=18, weight='bold', y=0.995)

# ============================================================================
# Save and Display
# ============================================================================
output_path = 'D区综合分析_ML_data.png'
plt.savefig(output_path, dpi=300, bbox_inches='tight', facecolor='white')
print(f"\n✅ Visualization saved: {output_path}")

print("\n" + "="*80)
print("STRATEGY D VISUALIZATION COMPLETE")
print("="*80)
print(f"\n📊 Generated comprehensive analysis with 15 charts")
print(f"📁 Output file: {output_path}")
print("\n💡 Key Insights:")
print(f"  • Average reduction rate: {df_summary['减排率'].mean():.1f}%")
print(f"  • Average payback period: {avg_payback:.1f} years")
print(f"  • Success rate: {success_rate:.1f}%")
print(f"  • Average automation level: {avg_automation:.2f}")
print(f"  • Most cost-effective approach among all zones")
print("\n" + "="*80)

plt.show()
